/**
 * Registration System API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnumerationItemDTO } from './enumeration-item-dto';
import { PlaceDTO } from './place-dto';


/**
 * @type EnumerationItemAggregateDTO
 * @export
 */
export type EnumerationItemAggregateDTO = EnumerationItemDTO | PlaceDTO;

