/**
 * Registration System API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EnumerationItemDTO { 
    id?: number;
    code?: string;
    name?: string;
    description?: string;
    ordering: number;
    hidden?: boolean;
    type: string;
}

