/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EnumerationItemPublicDTO { 
    enum_name: EnumerationItemPublicDTO.EnumNameEnum;
    code: string;
    description: string;
    ordering: number;
    visible: boolean;
}
export namespace EnumerationItemPublicDTO {
    export const EnumNameEnum = {
        RegEEventConditionType: 'REG_E_EVENT_CONDITION_TYPE',
        RegEEventDiscountType: 'REG_E_EVENT_DISCOUNT_TYPE',
        RegERelation: 'REG_E_RELATION',
        RegEShirtSize: 'REG_E_SHIRT_SIZE'
    } as const;
    export type EnumNameEnum = typeof EnumNameEnum[keyof typeof EnumNameEnum];
}


