/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EnumerationItemPublicDTO { 
    enum_name: EnumerationItemPublicDTO.EnumNameEnum;
    code: string;
    description: string;
    ordering: number;
    visible: boolean;
}
export namespace EnumerationItemPublicDTO {
    export type EnumNameEnum = 'REG_E_EVENT_CONDITION_TYPE' | 'REG_E_EVENT_DISCOUNT_TYPE' | 'REG_E_RELATION' | 'REG_E_SHIRT_SIZE';
    export const EnumNameEnum = {
        RegEEventConditionType: 'REG_E_EVENT_CONDITION_TYPE' as EnumNameEnum,
        RegEEventDiscountType: 'REG_E_EVENT_DISCOUNT_TYPE' as EnumNameEnum,
        RegERelation: 'REG_E_RELATION' as EnumNameEnum,
        RegEShirtSize: 'REG_E_SHIRT_SIZE' as EnumNameEnum
    };
}


