/**
 * Registration System API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnumerationItemAggregateDTO } from './enumeration-item-aggregate-dto';


export interface EnumerationDTO { 
    administrated?: boolean;
    values?: Array<EnumerationItemAggregateDTO>;
}

