/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EventTermCapacityResponsePublicDTO { 
    capacity?: number;
    confirmed?: number;
    registered?: number;
    available?: number;
}

