/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EventEventTermDTO { 
    createdAt?: string;
    uuid?: string;
    id?: number;
    name: string;
    place: string;
    eventType: EventEventTermDTO.EventTypeEnum;
    regStartAt: string;
    regEndAt: string;
    imageUrl?: string;
    discountType?: string;
}
export namespace EventEventTermDTO {
    export type EventTypeEnum = 'EVENT' | 'CAMP' | 'SCHOOL_CLIMB' | 'ECA';
    export const EventTypeEnum = {
        Event: 'EVENT' as EventTypeEnum,
        Camp: 'CAMP' as EventTypeEnum,
        SchoolClimb: 'SCHOOL_CLIMB' as EventTypeEnum,
        Eca: 'ECA' as EventTypeEnum
    };
}


