/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EventTermCapacityDTO { 
    eventTermId?: number;
    status?: EventTermCapacityDTO.StatusEnum;
    capacity?: number;
    registrations?: number;
    registeredCount?: number;
    confirmedCount?: number;
}
export namespace EventTermCapacityDTO {
    export const StatusEnum = {
        Concept: 'CONCEPT',
        Queue: 'QUEUE',
        Confirmed: 'CONFIRMED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


