/**
 * Registration System API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EventConditionDTO { 
    conditionType: EventConditionDTO.ConditionTypeEnum;
    minValue?: string;
    maxValue?: string;
    value?: string;
}
export namespace EventConditionDTO {
    export const ConditionTypeEnum = {
        YearBorn: 'YEAR_BORN'
    } as const;
    export type ConditionTypeEnum = typeof ConditionTypeEnum[keyof typeof ConditionTypeEnum];
}


