/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegistrationInternalDTO } from './registration-internal';


export interface EventTermInternalDTO { 
    id?: number;
    startAt?: string;
    endAt?: string;
    capacity: number;
    deposit: number;
    price: number;
    registrations?: Array<RegistrationInternalDTO>;
}

