/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EventTermEventPublicDTO } from './event-term-event-public';


export interface EventEventPublicDTO { 
    createdAt?: string;
    uuid?: string;
    name: string;
    details: string;
    place: string;
    eventType: EventEventPublicDTO.EventTypeEnum;
    regStartAt: string;
    regEndAt: string;
    imageUrl?: string;
    discountType?: string;
    terms?: Array<EventTermEventPublicDTO>;
}
export namespace EventEventPublicDTO {
    export const EventTypeEnum = {
        Event: 'EVENT',
        Camp: 'CAMP',
        SchoolClimb: 'SCHOOL_CLIMB',
        Eca: 'ECA'
    } as const;
    export type EventTypeEnum = typeof EventTypeEnum[keyof typeof EventTypeEnum];
}


