/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EventTermCapacityDTO } from './event-term-capacity';
import { EventDTO } from './event';
import { RegistrationDTO } from './registration';


export interface EventTermDTO { 
    id?: number;
    startAt?: string;
    endAt?: string;
    capacity: number;
    deposit: number;
    price: number;
    event?: EventDTO;
    registrations?: Set<RegistrationDTO>;
    currentCapacities?: Array<EventTermCapacityDTO>;
}

