/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EventTermEventInternalDTO } from './event-term-event-internal';


export interface EventEventInternalDTO { 
    createdAt?: string;
    uuid?: string;
    id?: number;
    name: string;
    place: string;
    eventType: EventEventInternalDTO.EventTypeEnum;
    regStartAt: string;
    regEndAt: string;
    imageUrl?: string;
    discountType?: string;
    terms?: Array<EventTermEventInternalDTO>;
}
export namespace EventEventInternalDTO {
    export const EventTypeEnum = {
        Event: 'EVENT',
        Camp: 'CAMP',
        SchoolClimb: 'SCHOOL_CLIMB',
        Eca: 'ECA'
    } as const;
    export type EventTypeEnum = typeof EventTypeEnum[keyof typeof EventTypeEnum];
}


