/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EventTermCapacityDTO } from './event-term-capacity';


export interface EventTermDTO { 
    id?: number;
    startAt?: string;
    endAt?: string;
    capacity: number;
    deposit: number;
    price: number;
    currentCapacities?: Array<EventTermCapacityDTO>;
}

