/**
 * Registration System API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EventConditionDTO } from './event-condition-dto';


export interface EventDTO { 
    id?: number;
    name: string;
    details: string;
    eventType: string;
    imageUrl?: string;
    registrationStarts: string;
    registrationEnds: string;
    placeCode: string;
    periodCode?: string;
    conditions?: Array<EventConditionDTO>;
    locked?: string;
    status?: EventDTO.StatusEnum;
    createdAt?: string;
    createdBy?: string;
    modifiedAt?: string;
    modifiedBy?: string;
}
export namespace EventDTO {
    export const StatusEnum = {
        Draft: 'DRAFT',
        Published: 'PUBLISHED',
        Cancelled: 'CANCELLED',
        Deleted: 'DELETED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


