/**
 * Registration System API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EventTermDTO { 
    id?: number;
    repeatType: EventTermDTO.RepeatTypeEnum;
    startDate: string;
    startTime: string;
    durationMinutes: number;
    endDate?: string;
    dayOfWeek?: EventTermDTO.DayOfWeekEnum;
    expectedTrainers?: Array<string>;
    deposit?: number;
    price: number;
    capacity: number;
    hasAttendance: boolean;
    eventId?: number;
}
export namespace EventTermDTO {
    export const RepeatTypeEnum = {
        Once: 'ONCE',
        Daily: 'DAILY',
        Weekly: 'WEEKLY'
    } as const;
    export type RepeatTypeEnum = typeof RepeatTypeEnum[keyof typeof RepeatTypeEnum];
    export const DayOfWeekEnum = {
        Monday: 'MONDAY',
        Tuesday: 'TUESDAY',
        Wednesday: 'WEDNESDAY',
        Thursday: 'THURSDAY',
        Friday: 'FRIDAY',
        Saturday: 'SATURDAY',
        Sunday: 'SUNDAY'
    } as const;
    export type DayOfWeekEnum = typeof DayOfWeekEnum[keyof typeof DayOfWeekEnum];
}


