/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GenericErrorDTO { 
    code?: string;
    status_code?: number;
    message?: string;
    parameters?: { [key: string]: object; };
}

