/**
 * Registration System API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EventDTO } from './event-dto';


export interface PageableResponseDTOEventDTO { 
    content?: Array<EventDTO>;
    pageNumber?: number;
    pageSize?: number;
    totalPages?: number;
    totalElements?: number;
}

