/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegistrationPublicDTO } from './registration-public';


export interface PaymentPublicDTO { 
    registration?: RegistrationPublicDTO;
    id?: number;
    price: number;
    deposit?: number;
    discountValue?: number;
    discountPercent?: number;
    depositPaid?: boolean;
    paid?: boolean;
    remainingValue?: number;
    variableSymbol?: string;
    finalPrice?: number;
    discountPercentValue?: number;
    hasDiscount?: boolean;
    hasDeposit?: boolean;
}

