/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PersonInternalDTO { 
    name: string;
    surname: string;
    dateOfBirth: string;
    healthNotes?: string;
    foodAllergyNotes?: string;
    shirtSize?: string;
    isIndependent?: boolean;
    fullName?: string;
}

