/**
 * Registration System API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnumerationItemDTO } from './enumeration-item-dto';


export interface PlaceDTO extends EnumerationItemDTO { 
    latitude: number;
    longitude: number;
}

