/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KnownPersonInternalDTO } from './known-person-internal';
import { PaymentInternalDTO } from './payment-internal';
import { PersonInternalDTO } from './person-internal';


export interface RegistrationInternalDTO { 
    createdAt?: string;
    uuid?: string;
    id?: number;
    status?: RegistrationInternalDTO.StatusEnum;
    name: string;
    surname: string;
    email: string;
    telPhone: string;
    people?: Array<PersonInternalDTO>;
    knownPeople?: Array<KnownPersonInternalDTO>;
    payment?: PaymentInternalDTO;
}
export namespace RegistrationInternalDTO {
    export type StatusEnum = 'CONCEPT' | 'QUEUE' | 'ACCEPTED' | 'CONFIRMED';
    export const StatusEnum = {
        Concept: 'CONCEPT' as StatusEnum,
        Queue: 'QUEUE' as StatusEnum,
        Accepted: 'ACCEPTED' as StatusEnum,
        Confirmed: 'CONFIRMED' as StatusEnum
    };
}


