/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentPublicDTO } from './payment-public';
import { KnownPersonPublicDTO } from './known-person-public';
import { PersonPublicDTO } from './person-public';


export interface RegistrationPublicDTO { 
    createdAt?: string;
    uuid?: string;
    status?: RegistrationPublicDTO.StatusEnum;
    name: string;
    surname: string;
    email: string;
    telPhone: string;
    consentGDPR: boolean;
    consentPhoto: boolean;
    emailConfirmSent?: boolean;
    emailPaymentInfoSent?: boolean;
    emailPaymentConfirmSent?: boolean;
    people?: Array<PersonPublicDTO>;
    knownPeople?: Array<KnownPersonPublicDTO>;
    payment?: PaymentPublicDTO;
}
export namespace RegistrationPublicDTO {
    export const StatusEnum = {
        Concept: 'CONCEPT',
        Queue: 'QUEUE',
        Confirmed: 'CONFIRMED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


