export * from './enumeration.service';
import { EnumerationRestService } from './enumeration.service';
export * from './event.service';
import { EventRestService } from './event.service';
export * from './event-term.service';
import { EventTermRestService } from './event-term.service';
export * from './health.service';
import { HealthRestService } from './health.service';
export * from './period.service';
import { PeriodRestService } from './period.service';
export const APIS = [EnumerationRestService, EventRestService, EventTermRestService, HealthRestService, PeriodRestService];
