/**
 * Registration System API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { EnumerationItemAggregateDTO } from '../model/enumeration-item-aggregate-dto';
// @ts-ignore
import { EnumerationItemDTO } from '../model/enumeration-item-dto';
// @ts-ignore
import { GenericErrorDTO } from '../model/generic-error-dto';
// @ts-ignore
import { PlaceDTO } from '../model/place-dto';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class EnumerationRestService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * @param enumName 
     * @param enumerationItemDTOPlaceDTO 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createEnumItem(enumName: 'REG_EVENT_CONDITION_TYPE' | 'REG_EVENT_DISCOUNT_TYPE' | 'REG_EVENT_TYPE' | 'REG_EVENT_TERM_TAG' | 'REG_PLACE' | 'REG_PERIOD' | 'REG_RELATION' | 'REG_SHIRT_SIZE', enumerationItemDTOPlaceDTO: EnumerationItemDTO | PlaceDTO, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | '*/*', context?: HttpContext, transferCache?: boolean}): Observable<EnumerationItemAggregateDTO>;
    public createEnumItem(enumName: 'REG_EVENT_CONDITION_TYPE' | 'REG_EVENT_DISCOUNT_TYPE' | 'REG_EVENT_TYPE' | 'REG_EVENT_TERM_TAG' | 'REG_PLACE' | 'REG_PERIOD' | 'REG_RELATION' | 'REG_SHIRT_SIZE', enumerationItemDTOPlaceDTO: EnumerationItemDTO | PlaceDTO, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<EnumerationItemAggregateDTO>>;
    public createEnumItem(enumName: 'REG_EVENT_CONDITION_TYPE' | 'REG_EVENT_DISCOUNT_TYPE' | 'REG_EVENT_TYPE' | 'REG_EVENT_TERM_TAG' | 'REG_PLACE' | 'REG_PERIOD' | 'REG_RELATION' | 'REG_SHIRT_SIZE', enumerationItemDTOPlaceDTO: EnumerationItemDTO | PlaceDTO, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<EnumerationItemAggregateDTO>>;
    public createEnumItem(enumName: 'REG_EVENT_CONDITION_TYPE' | 'REG_EVENT_DISCOUNT_TYPE' | 'REG_EVENT_TYPE' | 'REG_EVENT_TERM_TAG' | 'REG_PLACE' | 'REG_PERIOD' | 'REG_RELATION' | 'REG_SHIRT_SIZE', enumerationItemDTOPlaceDTO: EnumerationItemDTO | PlaceDTO, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json' | '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (enumName === null || enumName === undefined) {
            throw new Error('Required parameter enumName was null or undefined when calling createEnumItem.');
        }
        if (enumerationItemDTOPlaceDTO === null || enumerationItemDTOPlaceDTO === undefined) {
            throw new Error('Required parameter enumerationItemDTOPlaceDTO was null or undefined when calling createEnumItem.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json',
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/enumerations/${this.configuration.encodeParam({name: "enumName", value: enumName, in: "path", style: "simple", explode: false, dataType: "'REG_EVENT_CONDITION_TYPE' | 'REG_EVENT_DISCOUNT_TYPE' | 'REG_EVENT_TYPE' | 'REG_EVENT_TERM_TAG' | 'REG_PLACE' | 'REG_PERIOD' | 'REG_RELATION' | 'REG_SHIRT_SIZE'", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<EnumerationItemAggregateDTO>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: enumerationItemDTOPlaceDTO,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param enumName 
     * @param enumCode 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteEnumItem(enumName: 'REG_EVENT_CONDITION_TYPE' | 'REG_EVENT_DISCOUNT_TYPE' | 'REG_EVENT_TYPE' | 'REG_EVENT_TERM_TAG' | 'REG_PLACE' | 'REG_PERIOD' | 'REG_RELATION' | 'REG_SHIRT_SIZE', enumCode: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | '*/*', context?: HttpContext, transferCache?: boolean}): Observable<Array<EnumerationItemAggregateDTO>>;
    public deleteEnumItem(enumName: 'REG_EVENT_CONDITION_TYPE' | 'REG_EVENT_DISCOUNT_TYPE' | 'REG_EVENT_TYPE' | 'REG_EVENT_TERM_TAG' | 'REG_PLACE' | 'REG_PERIOD' | 'REG_RELATION' | 'REG_SHIRT_SIZE', enumCode: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<EnumerationItemAggregateDTO>>>;
    public deleteEnumItem(enumName: 'REG_EVENT_CONDITION_TYPE' | 'REG_EVENT_DISCOUNT_TYPE' | 'REG_EVENT_TYPE' | 'REG_EVENT_TERM_TAG' | 'REG_PLACE' | 'REG_PERIOD' | 'REG_RELATION' | 'REG_SHIRT_SIZE', enumCode: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<EnumerationItemAggregateDTO>>>;
    public deleteEnumItem(enumName: 'REG_EVENT_CONDITION_TYPE' | 'REG_EVENT_DISCOUNT_TYPE' | 'REG_EVENT_TYPE' | 'REG_EVENT_TERM_TAG' | 'REG_PLACE' | 'REG_PERIOD' | 'REG_RELATION' | 'REG_SHIRT_SIZE', enumCode: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json' | '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (enumName === null || enumName === undefined) {
            throw new Error('Required parameter enumName was null or undefined when calling deleteEnumItem.');
        }
        if (enumCode === null || enumCode === undefined) {
            throw new Error('Required parameter enumCode was null or undefined when calling deleteEnumItem.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json',
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/enumerations/${this.configuration.encodeParam({name: "enumName", value: enumName, in: "path", style: "simple", explode: false, dataType: "'REG_EVENT_CONDITION_TYPE' | 'REG_EVENT_DISCOUNT_TYPE' | 'REG_EVENT_TYPE' | 'REG_EVENT_TERM_TAG' | 'REG_PLACE' | 'REG_PERIOD' | 'REG_RELATION' | 'REG_SHIRT_SIZE'", dataFormat: undefined})}/${this.configuration.encodeParam({name: "enumCode", value: enumCode, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/hide`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Array<EnumerationItemAggregateDTO>>('delete', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param enumName 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getEnumItems(enumName: 'REG_EVENT_CONDITION_TYPE' | 'REG_EVENT_DISCOUNT_TYPE' | 'REG_EVENT_TYPE' | 'REG_EVENT_TERM_TAG' | 'REG_PLACE' | 'REG_PERIOD' | 'REG_RELATION' | 'REG_SHIRT_SIZE', observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | '*/*', context?: HttpContext, transferCache?: boolean}): Observable<Array<EnumerationItemAggregateDTO>>;
    public getEnumItems(enumName: 'REG_EVENT_CONDITION_TYPE' | 'REG_EVENT_DISCOUNT_TYPE' | 'REG_EVENT_TYPE' | 'REG_EVENT_TERM_TAG' | 'REG_PLACE' | 'REG_PERIOD' | 'REG_RELATION' | 'REG_SHIRT_SIZE', observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<EnumerationItemAggregateDTO>>>;
    public getEnumItems(enumName: 'REG_EVENT_CONDITION_TYPE' | 'REG_EVENT_DISCOUNT_TYPE' | 'REG_EVENT_TYPE' | 'REG_EVENT_TERM_TAG' | 'REG_PLACE' | 'REG_PERIOD' | 'REG_RELATION' | 'REG_SHIRT_SIZE', observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<EnumerationItemAggregateDTO>>>;
    public getEnumItems(enumName: 'REG_EVENT_CONDITION_TYPE' | 'REG_EVENT_DISCOUNT_TYPE' | 'REG_EVENT_TYPE' | 'REG_EVENT_TERM_TAG' | 'REG_PLACE' | 'REG_PERIOD' | 'REG_RELATION' | 'REG_SHIRT_SIZE', observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json' | '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (enumName === null || enumName === undefined) {
            throw new Error('Required parameter enumName was null or undefined when calling getEnumItems.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json',
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/enumerations/items/name/${this.configuration.encodeParam({name: "enumName", value: enumName, in: "path", style: "simple", explode: false, dataType: "'REG_EVENT_CONDITION_TYPE' | 'REG_EVENT_DISCOUNT_TYPE' | 'REG_EVENT_TYPE' | 'REG_EVENT_TERM_TAG' | 'REG_PLACE' | 'REG_PERIOD' | 'REG_RELATION' | 'REG_SHIRT_SIZE'", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Array<EnumerationItemAggregateDTO>>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getItemsAdministrated(observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | '*/*', context?: HttpContext, transferCache?: boolean}): Observable<{ [key: string]: Array<EnumerationItemAggregateDTO>; }>;
    public getItemsAdministrated(observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<{ [key: string]: Array<EnumerationItemAggregateDTO>; }>>;
    public getItemsAdministrated(observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<{ [key: string]: Array<EnumerationItemAggregateDTO>; }>>;
    public getItemsAdministrated(observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json' | '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json',
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/enumerations/items/administrated`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<{ [key: string]: Array<EnumerationItemAggregateDTO>; }>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getNamesAdministrated(observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | '*/*', context?: HttpContext, transferCache?: boolean}): Observable<Array<string>>;
    public getNamesAdministrated(observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<string>>>;
    public getNamesAdministrated(observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<string>>>;
    public getNamesAdministrated(observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json' | '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json',
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/enumerations/names/administrated`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Array<string>>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

}
