name: "horizon"
services:
  frontend:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: "horizon/caddy-web"
    container_name: "horizon_web"
    restart: unless-stopped
    ports:
      - "${HOR_PORT:?required}:80"
      - "${HOR_SECURE_PORT:?required}:443"
    networks:
      - horizon_network
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    environment:
      HOR_HOSTNAME: ${HOR_HOSTNAME:?required}
      HOR_PORT: ${HOR_PORT}
      HOR_SECURE_PORT: ${HOR_SECURE_PORT}
      HOR_BE_CONTAINER_NAME: ${HOR_BE_CONTAINER_NAME:horizon_backend}
      HOR_BE_PORT: ${HOR_BE_PORT:8080}
networks:
  horizon_network:
    name: horizon_network
    driver: bridge
volumes:
  caddy_data:
    name: horizon_caddy_data
  caddy_config:
    name: horizon_caddy_config
