name: "registration"
services:
  frontend:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: "registration/caddy-web"
    container_name: "registration_web"
    restart: unless-stopped
    ports:
      - "${REG_WEB_PORT:-80}:80"
      - "${REG_WEB_SECURE_PORT:-443}:443"
    networks:
      - registration_network
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    environment:
      REG_WEB_HOSTNAME: ${REG_WEB_HOSTNAME:?required}
      REG_WEB_PORT: ${REG_WEB_PORT:-80}
      REG_WEB_SECURE_PORT: ${REG_WEB_SECURE_PORT:-443}
      REG_SYS_CONTAINER_NAME: ${REG_SYS_CONTAINER_NAME:-registration_backend}
      REG_SYS_PORT: ${REG_SYS_PORT:-8080}
networks:
  registration_network:
    name: registration_network
    driver: bridge
volumes:
  caddy_data:
    name: registration_caddy_data
  caddy_config:
    name: registration_caddy_config
