/**
 * Enumeration names from backend.
 */
export enum EnumerationName {
  REG_EVENT_CONDITION_TYPE = 'REG_EVENT_CONDITION_TYPE',
  REG_EVENT_DISCOUNT_TYPE = 'REG_EVENT_DISCOUNT_TYPE',
  REG_EVENT_TERM_TAG = 'REG_EVENT_TERM_TAG',
  REG_PLACE = 'REG_PLACE',
  REG_PERIOD = 'REG_PERIOD',
  REG_RELATION = 'REG_RELATION',
  REG_SHIRT_SIZE = 'REG_SHIRT_SIZE'
}